const inimigos = [
    {
        tipo: "Dragão jovem",
        img_path: "",
        local_ataque: 'Castelo abandonado',
        premio: '30 moedas de ouro, pele de dragão',
        ataque: 5,
        defesa: 12,
        vida: 50,
        exaustao: 0,
    },
    {
        tipo: "Minotauro",
        img_path: "",
        local_ataque: 'Labirinto subterrâneo',
        premio: 'Chifre de Minotauro (artefato mágico), 20 moedas de ouro',
        ataque: 8,
        defesa: 10,
        vida: 30,
        exaustao: 0,
    },
    {
        tipo: "Banshee",
        img_path: "",
        local_ataque: 'Cemitério assombrado',
        premio: 'Amuleto de proteção contra a morte, 15 moedas de ouro',
        ataque: 6,
        defesa: 9,
        vida: 18,
        exaustao: 0,
    },
    {
        tipo: "Beholder",
        img_path: "",
        local_ataque: 'Torre de feiticeiro',
        premio: 'Olho do Beholder (artefato mágico), 50 moedas de ouro',
        ataque: 12,
        defesa: 14,
        vida: 30,
        exaustao: 0,
    },
    {
        tipo: "Gigante de Gelo",
        img_path: "",
        local_ataque: 'Montanhas nevadas',
        premio: 'Martelo de guerra gigante, 30 moedas de ouro',
        ataque: 10,
        defesa: 15,
        vida: 40,
        exaustao: 0,
    },
    {
        tipo: "Kraken",
        img_path: "",
        local_ataque: 'Profundezas do oceano',
        premio: 'Escamas de Kraken (material para armaduras mágicas), 100 moedas de ouro',
        ataque: 15,
        defesa: 17,
        vida: 60,
        exaustao: 0,
    },
    {
        tipo: "Vampira solitária",
        img_path: "",
        local_ataque: 'Ruas de Baldurs Gate',
        premio: '50 moedas de ouro, capa mágica',
        ataque: 2,
        defesa: 10,
        vida: 35,
        exaustao: 0,
    },
    {
        tipo: "Goblin Capitão",
        img_path: "",
        local_ataque: 'Ruínas antigas',
        premio: 'Arco curto, 5 moedas de cobre',
        ataque: 4,
        defesa: 8,
        vida: 20,
        exaustao: 0,
    }
]